version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: loofah
    versions:
    - 2.9.0
